# Generated by Django 4.1.6 on 2023-09-16 10:37

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filehandler',
            name='file_upload',
            field=models.FileField(upload_to=core.models.file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx'])]),
        ),
    ]
